#!/usr/bin/env python3
"""Extract weekly LMS parameters (0–104 weeks) from the WHO Child Growth
Standards expanded tables into src/domain/who.data.ts.

Usage: python3 scripts/who-lms.py <dir with the six xlsx files>
Source: https://www.who.int/tools/child-growth-standards/standards
"""
import sys, zipfile, xml.etree.ElementTree as ET, json, pathlib

NS = {'m': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
FILES = {
    ('weight', 'boy'): 'wfa-boys-zscore-expanded-tables.xlsx',
    ('weight', 'girl'): 'wfa-girls-zscore-expanded-tables.xlsx',
    ('length', 'boy'): 'lhfa-boys-zscore-expanded-tables.xlsx',
    ('length', 'girl'): 'lhfa-girls-zscore-expanded-tables.xlsx',
    ('head', 'boy'): 'hcfa-boys-zscore-expanded-tables.xlsx',
    ('head', 'girl'): 'hcfa-girls-zscore-expanded-tables.xlsx',
}
WEEKS = 104

def rows(path):
    z = zipfile.ZipFile(path)
    shared = []
    if 'xl/sharedStrings.xml' in z.namelist():
        for si in ET.fromstring(z.read('xl/sharedStrings.xml')).findall('m:si', NS):
            shared.append(''.join(t.text or '' for t in si.iter('{%s}t' % NS['m'])))
    root = ET.fromstring(z.read('xl/worksheets/sheet1.xml'))
    out = []
    for r in root.find('m:sheetData', NS):
        vals = []
        for c in r:
            v = c.find('m:v', NS)
            vals.append('' if v is None else (shared[int(v.text)] if c.get('t') == 's' else v.text))
        out.append(vals)
    return out

src = pathlib.Path(sys.argv[1])
data = {}
for (measure, sex), name in FILES.items():
    table = rows(src / name)
    header = table[0]
    di, li, mi, si = header.index('Day'), header.index('L'), header.index('M'), header.index('S')
    by_day = {int(r[di]): (float(r[li]), float(r[mi]), float(r[si])) for r in table[1:] if r[di]}
    data.setdefault(measure, {})[sex] = [[round(v, 5) for v in by_day[w * 7]] for w in range(WEEKS + 1)]

out = pathlib.Path(__file__).resolve().parent.parent / 'src' / 'domain' / 'who.data.ts'
body = json.dumps(data, separators=(',', ':'))
out.write_text(
    '// Generated by scripts/who-lms.py from the WHO Child Growth Standards\n'
    '// (https://www.who.int/tools/child-growth-standards). Weekly LMS values,\n'
    f'// weeks 0..{WEEKS}, as [L, M, S]. Do not edit by hand.\n'
    'export type Sex = "boy" | "girl";\n'
    'export type Measure = "weight" | "length" | "head";\n'
    'export type LMS = [number, number, number];\n'
    f'export const WHO_WEEKS = {WEEKS};\n'
    f'export const WHO_LMS: Record<Measure, Record<Sex, LMS[]>> = {body};\n'
)
print(out, out.stat().st_size, 'bytes')
